#!/bin/bash

# Copyright (C) 2015 Tokyo Opensource Robotics Kyokai Association (TORK)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DATE=`date`
cat <<EOF
###
### THIS FILE IS AUTOMATICALLY GENERATED by $0 ${PWD} ${DATE}
###
pepper:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
EOF

cat <<EOF

  # Position Controllers (arms) ---------------------------------------
EOF
for joint in LShoulderPitch, LShoulderRoll, LElbowYaw, LElbowRoll, LWristYaw, RShoulderPitch, RShoulderRoll, RElbowYaw, RElbowRoll, RWristYaw; do
    cat <<EOF
  ${joint}_position_controller:
    type: effort_controllers/JointPositionController
    joint: ${joint}
    pid: {p: 100, i: 0.01, d: 5.0}
EOF
done

for arm in L R; do
    joint_list="${arm}ShoulderPitch ${arm}ShoulderRoll ${arm}ElbowYaw ${arm}ElbowRoll ${arm}WristYaw";
    cat <<EOF

  # Trajectory Controllers ---------------------------------------
  ${arm}_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
EOF
    for joint in ${joint_list}; do
    cat <<EOF
      - ${joint}
EOF
    done
    cat <<EOF
    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.02 # Override default
EOF
    for joint in ${joint_list}; do
        cat <<EOF
      ${joint}:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.02                     # Not enforced if unspecified
EOF
    done
    cat <<EOF

    gains: # Required because we're controlling an effort interface
EOF
    for joint in ${joint_list}; do
    cat <<EOF
      ${joint}: {p: 500, i: 5, d: 1}
EOF
    done
    cat <<EOF
    state_publish_rate:  100            # Override default
    action_monitor_rate: 100            # Override default
    stop_trajectory_duration: 0        # Override default

EOF
done
